Adds functionality to support shortcuts for adding all members of a g…
instructure/canvas-lms pull request #1765
Opened 2020-12-03 21:20 UTC by dittonjs

…roup or section to a conference.

This change adds checkboxes for groups and sections to the members list section of the dialog for creating / editing a conference. These checkboxes are "shortcuts" that allow the user to quickly add all members of a specific section or group to a conference. These shortcuts are implemented client side and the  model for conferences is unchanged.

Test Plan:
	- Make sure the conferences feature is enabled
	- In a course open the dialog to create a new conference
	- Uncheck the "Invite All" box
	- Verify the following in the member list:
		- A checkbox for each section should appear in the "Sections" partition (only if there is more than one section in the course)
		- A checkbox for each group should appear in the "Groups" partition (only if there is at least one section in the course)
		- The headers for "Sections" and "Groups" should only appear if there is atleast item in the respective partition
		- The header for "Users" should only appear if one or more of the other partitions is present
		- Checking the box for section / group also checks the boxes for each of the users in that section / group
		- Unchecking the box for section / group also unchecks the boxes for each of the users in that section / group provided that another section / group that contains that user isn't also checked
		- If a user is added to the conference via a section or group you should not be able to uncheck the checkbox for that user.

2020-12-03 21:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/canvas-lms?pullRequest=1765) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/canvas-lms?pullRequest=1765) before we can accept your contribution.<br/><hr/>**Joseph Ditton** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/canvas-lms?pullRequest=1765) it.</sub>

2020-12-03 22:31 UTC, ffdixon commented
Here's a video demonstrating the feature in action.  

https://youtu.be/lzgkyH1lVHc

2020-12-11 00:45 UTC, fadedmax approved these changes
LGTM

2021-02-24 18:34 UTC, blunckr commented
Hello, any idea when this might be merged? I'm not sure what your processes are.

2021-04-19 20:52 UTC, jbasdf commented
Any update on this? Is there anything we can do to help get this merged in?

2021-04-19 21:03 UTC, simonista commented
Hi, thanks for the ping and sorry for the slow response. Let me run this by the product manager for conferences and make sure this is functionality they want to add.

2021-04-19 21:35 UTC, ffdixon commented
Thanks Simon.  This feature has been requested by a number large customers of Canvas Conferences and we sponsored the work to help Instructure get this feature in place.  We would like to see this go through the internal review process, support you however we can, make some customers very happy.

We'll fix the merge conflicts as well.

2021-07-01 16:52 UTC, cguanzon commented on app/controllers/conferences_controller.rb
> +        @sections = @context.course_sections
preload participants

2021-07-01 16:52 UTC, cguanzon commented on app/controllers/conferences_controller.rb
> +        @groups = @context.active_groups
preload participating users in context

2021-07-06 16:38 UTC, cguanzon commented
the following tests failed:

[2021-07-06T16:17:59.161Z] 1) sections should appear in member list if course has more than one section

[2021-07-06T16:17:59.162Z]      EditConferenceView

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:204:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:205:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 2) groups should appear in member list if course has one or more groups

[2021-07-06T16:17:59.162Z]      EditConferenceView

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:239:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 3) checking/unchecking a section also checks/unchecks the members that are in that section

[2021-07-06T16:17:59.162Z]      EditConferenceView

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:257:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 4) checking/unchecking a groups also checks/unchecks the members that are in that group

[2021-07-06T16:17:59.162Z]      EditConferenceView

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:276:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 5) unchecking a group only unchecks members that have not been selected by section also

[2021-07-06T16:17:59.162Z]      EditConferenceView

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:296:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:297:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:299:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z] 6) unchecking a section only unchecks members that have not been selected by group also

[2021-07-06T16:17:59.162Z]      EditConferenceView

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected: true

[2021-07-06T16:17:59.162Z] Actual: false

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:2194:12

[2021-07-06T16:17:59.162Z]     at Object.eval (webpack:///./spec/javascripts/jsx/conferences/EditConferenceViewSpec.js?:317:3)

[2021-07-06T16:17:59.162Z]     at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)

[2021-07-06T16:17:59.162Z]     at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)

[2021-07-06T16:17:59.162Z]     at node_modules/qunitjs/qunit/qunit.js:970:11

[2021-07-06T16:17:59.162Z]     at process (node_modules/qunitjs/qunit/qunit.js:629:24)

[2021-07-06T16:17:59.162Z] 

[2021-07-06T16:17:59.162Z]      failed, expected argument to be truthy, was: false

[2021-07-06T16:17:59.162Z] Expected [...]

2021-07-06 16:40 UTC, cguanzon requested changes
tests here https://github.com/instructure/canvas-lms/pull/1765/files#:~:text=spec/javascripts/jsx/conferences/EditConferenceViewSpec.js are failing for us

please check and make sure they pass

2021-07-29 14:36 UTC, bfcoder commented
@cguanzon I'm not seeing the same failures.

```
  EditConferenceView
    ✓ updateConferenceUserSettingDetailsForConference localizes values for datepicker settings (45ms)
    ✓ #show sets the proper title for new conferences (119ms)
    ✓ #show sets the proper title for editing conferences (87ms)
    ✓ #show sets localized durataion when editing conference (93ms)
    ✓ "remove observers" modifies "invite all course members" (104ms)
    ✓ sections should appear in member list if course has more than one section (90ms)
    ✓ sections should not appear in member list if course has only section (81ms)
    ✓ groups should appear in member list if course has one or more groups (189ms)
    ✓ checking/unchecking a section also checks/unchecks the members that are in that section (91ms)
    ✓ checking/unchecking a groups also checks/unchecks the members that are in that group (91ms)
    ✓ unchecking a group only unchecks members that have not been selected by section also (89ms)
    ✓ unchecking a section only unchecks members that have not been selected by group also (87ms)
    ✓ While editing a conference the box for a group should be checked and disabled if everyone in the group is a participant (82ms)
    ✓ While editing a conference the box for a section should be checked and disabled if everyone in the section is a participant (87ms)
    ✓ While editing a conference unchecking a group should only uncheck members who are not a part of the existing conference (86ms)
    ✓ While editing a conference unchecking a section should only uncheck member who are not a part of the existing conference (91ms)
    ✓ while context_is_group = true no sections or groups should appear in the member list (91ms)

Chrome 92.0.4515 (Linux 0.0.0): Executed 17 of 17 SUCCESS (1.609 secs / 1.603 secs)
```

I'm running the specs with `yarn jspec-watch spec/javascripts/jsx/conferences/EditConferenceViewSpec.js`. How are you running them that you are seeing these failures?

Here are my versions:
```
yarn --version
1.22.5

node --version
v14.16.0
```

Thanks!

2021-08-20 17:42 UTC, closed without merging

2021-08-20 17:43 UTC, roor0 commented
this was merged into canvas-lms 8a3c737b92b59721d5bc1c09a15aa32c8f0e63eb