Update data service event ( submission_updated ) documentation
instructure/canvas-lms pull request #1943
Opened 2021-09-27 16:45 UTC by johnsalzy

## Summary of the commit

Change the '|' to a ',' as it was attempting to make a new table column, causing documentation data to be cut off.

## Screenshots

#### Documentation Before Fix ( Web Preview )
![documentation before fix web preview](https://user-images.githubusercontent.com/47669041/134950621-ec3a5536-efc8-4f16-aef6-70b2651b53cf.png)

#### Documentation Before Fix ( Rendered Markdown Preview )
![documentation before fix](https://user-images.githubusercontent.com/47669041/134950269-49fae15c-d848-4463-b19e-75f12e1dd41e.png)

#### Documentation After Fix ( Rendered Markdown Preview )
![documentation after fix](https://user-images.githubusercontent.com/47669041/134950330-8dceec9e-6fb3-4d69-8726-fc6fce95a559.png)

## Test Plan:
 - Pull code
 - Render new markdown file and ensure new output is correct
 - Render it for the web preview

2021-09-27 16:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/canvas-lms?pullRequest=1943) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/canvas-lms?pullRequest=1943) before we can accept your contribution.<br/><hr/>**John S** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/canvas-lms?pullRequest=1943) it.</sub>

2022-01-27 17:34 UTC, spencerolson requested changes
Hi @johnsalzy thanks for catching and fixing this!

So the way that this portion of our API docs are generated are:
1. A change is made to the `.json` file (in this case, `doc/api/data_services/json/canvas/event-types/submission_updated.json`)
2. We run `bundle exec rails doc:api` to generate the markdown (in this case, `doc/api/data_services/md/dynamic/data_service_canvas_submission.md`)
3. The resulting changes are committed

The way the commit is as-is, if we run `bundle exec rails doc:api`, the change will be reverted in the generated markdown file because the change was not applied to the `.json` file. So, you just need to apply the same change (replacing `|` with `,`) in `doc/api/data_services/json/canvas/event-types/submission_updated.json`. Let me know if you have any questions, thanks!

2022-01-28 18:42 UTC, scoutskylar commented
I made the requested changes at https://github.com/instructure/canvas-lms/commit/738060a88489d8a8024d6f9f291b1f465c991c9f

2022-02-01 23:20 UTC, scoutskylar commented
I made the requested changes in a new pull request, which does not need conflicts resolved: https://github.com/instructure/canvas-lms/pull/2011

2022-02-02 15:39 UTC, closed without merging